import Head from 'next/head';
import React, { useState } from 'react';
import api from '../util/api';
import { logIn } from '../util/auth';

const API_URL = 'http://localhost:8000/';

export default function Home() {
    let [email, setEmail] = useState('');
    let [password, setPassword] = useState('');

    const handleSubmit = async e => {
        e.preventDefault();

        const headers = {
            Accept: 'application/json'
        };

        let data = new FormData();
        data.append('email', email);
        data.append('password', password);

        let result = api.get(`${API_URL}api/csrf-cookie`).then(() => {
            api.post(`${API_URL}api/login`, {
                headers,
                email: email,
                password: password
            }).then(response => {
                if (response.data.error) {
                    console.error(response.data.error);
                } else {
                    //SET TOKEN IN A CONTEXT

                    // setToken(response.data.token);
                    // console.log(token);
                    logIn(response.data.token);
                }
            });
        });

        let response = result.data;

        console.log(response);

        // if (response['success']) {
        //     console.log('Login Successful');
        //     login_token = response['token'];
        // } else {
        //     console.log('Failed to Login');
        // }
    };

    return (
        <div>
            <Head>
                <title>Photoboy</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="container flex gap-6">
                <h1>Share moments, not data</h1>

                <form onSubmit={e => handleSubmit(e)} method="post">
                    <label htmlFor="email">Email Address:</label>
                    <input
                        onInput={e => setEmail(e.target.value)}
                        type="email"
                        name="email"
                        id="email"
                    />

                    <label htmlFor="password">Password:</label>
                    <input
                        onInput={e => setPassword(e.target.value)}
                        type="password"
                        name="password"
                        id="password"
                    />
                    <button type="submit">Log in</button>
                </form>
            </div>
        </div>
    );
}
